baseURL = 'https://lemire.github.io/inf1220-hugo/'
languageCode = 'fr'
defaultContentLanguage = 'fr'

title = "INF 1220 - Introduction à la programmation"
theme = 'hugo-book'

# --- Paramètres du thème hugo-book ---
[params]
BookMenuBundle = "book"
BookToC = true
BookSearch = true
javaRunnerEndpoint = "https://flask-service-inf1220-java.90qakjuvfj4f8.ca-central-1.cs.amazonlightsail.com/run"
math = true
BookLogo = "livre.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
